const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {chromium}=require('playwright');
const base=process.env.SITE_URL||pathToFileURL(path.resolve(__dirname,'../web/index.html')).href;
const sample='CAQAAAAAAAAAAAAAAAAAAAAAAADswMWGjZmZmxMbwMzYmZAAAAAAAAAAYmZ2mBjZGLzYmhlFTzEDmZAQAMLz2CYsZAAYMjZMYgZGYCG';
(async()=>{
 const launch={headless:true};if(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE)launch.executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE;
 if(process.env.SITE_URL&&process.env.HTTPS_PROXY)launch.proxy={server:process.env.HTTPS_PROXY};
 const browser=await chromium.launch(launch),errors=[];
 const shot=async(page,name)=>{if(process.env.QA_SCREENSHOTS){fs.mkdirSync(process.env.QA_SCREENSHOTS,{recursive:true});await page.screenshot({path:path.join(process.env.QA_SCREENSHOTS,name+'.png'),fullPage:true});}};
 try{for(const width of [1440,390,320]){
  const page=await browser.newPage({viewport:{width,height:1000},hasTouch:width<600,isMobile:width<600,ignoreHTTPSErrors:true});
  page.on('pageerror',e=>errors.push(e.message));
  if(!process.env.SITE_URL)await page.route('https://**/*',r=>r.abort());
  await page.goto(base,{waitUntil:'domcontentloaded'});
  assert.equal(await page.locator('#welcomePanel').isVisible(),true);
  assert.equal(await page.locator('.welcome-class').count(),13);
  assert.equal(await page.locator('#classSelect').isVisible(),false);
  await shot(page,`welcome-${width}`);
  await page.locator('#welcomePanel [data-open-import]').click();
  await page.locator('#buildString').fill(sample);
  await page.locator('#importBuildApply').click();
  await page.locator('#buildDialog').waitFor({state:'hidden'});
  assert.equal(await page.locator('#heroSelect').inputValue(),'Voidweaver');
  assert.equal(new URLSearchParams(new URL(page.url()).hash.slice(1)).get('build'),sample);
  assert.equal((await page.locator('#classPoints').textContent()).trim(),'34/34');
  assert.equal((await page.locator('#specPoints').textContent()).trim(),'34/34');
  await page.locator('#exportBuild').click();
  assert.equal(await page.locator('#buildString').inputValue(),sample);
  await shot(page,`export-${width}`);
  await page.locator('#buildDialog [data-close-dialog]').click();
  const before=page.url();
  await page.reload();
  await page.waitForFunction(()=>document.querySelector('#heroSelect').value==='Voidweaver');
  assert.equal(page.url(),before);
  await page.locator('.documentation-link').click();
  await page.frameLocator('#docsFrame').locator('#spec-aura').waitFor();
  await page.frameLocator('#docsFrame').locator('body').press('Escape');
  await page.locator('#docsDialog').waitFor({state:'hidden'});
  assert.equal(page.url(),before);
  await page.locator('[data-open-import]:visible').click();
  await page.locator('#buildString').fill(sample.slice(0,-3));
  await page.locator('#importBuildApply').click();
  await page.waitForFunction(()=>document.querySelector('#buildDialogError').textContent.length>0);
  assert.equal(page.url(),before,'Failed import must preserve build');
  await page.locator('#buildDialog [data-close-dialog]').click();
  await page.locator('[data-tab="compendium"]').click();
  await page.locator('#classSelect').selectOption('Druid');
  await page.waitForFunction(()=>!document.querySelector('#specSelect').disabled&&document.querySelector('#treeTitle').textContent.includes('Druid'));
  await page.locator('[data-tab="tree"]').click();
  await page.waitForFunction(()=>[...document.querySelectorAll('.tree-canvas')].every(el=>el.getBoundingClientRect().width>200));
  const geometry=await page.locator('.tree-canvas').evaluateAll(trees=>trees.map(tree=>{
   const rect=tree.getBoundingClientRect();return [...tree.querySelectorAll('.talent-node')].every(n=>{const r=n.getBoundingClientRect();return r.left>=rect.left-1&&r.right<=rect.right+1;});
  }));
  assert.ok(geometry.every(Boolean),'Hidden-tab class switch geometry');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
  await shot(page,`class-switch-${width}`);
  await page.close();console.log(`Build UI checks passed at ${width}px`);
 }assert.deepEqual(errors,[]);}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
